### PR TITLE
Add post-insert hook

### PR DESCRIPTION
**Pull request by cashpw**
I included docs in this one. My bad on the last (#20).

### CODE REVIEW

**Comment by cashpw** [comment]
My primary use case for this is piping whisper's transcription directly into [gptel](https://github.com/karthink/gptel).

**Comment by natrys** [comment]
That's pretty cool. I felt the need for this recently (#19) actually. Thanks a lot for doing it.

(I had to resolve conflict after I made some doc change. Then I locally squashed the commits but github now can't pick up the merge here, sorry about that.)

Anyway, I wonder if it now makes sense to rename post-process-hook to after-transcription-hook for more clarity.

**Comment by cashpw** [comment]
Renaming is all good by me! I can make the change or you can, whichever is
easier.

**Comment by natrys** [comment]
A little late but I got to it. Small heads up, had to rename your `whisper-post-insert-hook` to `whisper-after-insert-hook` for consistency with other renames.

**Pull request closed without merging**
